# Generated by Django 5.1.3 on 2024-11-18 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_proyecto_options_alter_cliente_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='Contacto',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
