# Generated by Django 5.1.3 on 2024-11-24 02:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_cita'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cita',
            old_name='descripción',
            new_name='descripcion',
        ),
        migrations.AlterField(
            model_name='cita',
            name='Cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to=settings.AUTH_USER_MODEL),
        ),
    ]
