# Generated by Django 5.1.3 on 2024-11-24 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_descripción_cita_descripcion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cita',
            old_name='Cliente',
            new_name='usuario',
        ),
    ]
